ballet: add BLAKE3 hashing support
updates to blake3

add blake3 impl

cleanup, add comments

Memory leak detection and other fd_alloc features

- fd_alloc_is_empty APIs and corresponding "query leak" fd_alloc_ctl
  command to allow programmatic, command line and/or scripted allocation
  leak detection of running and/or terminated programs.

- Related fd_alloc_compact and corresponding "compact" fd_alloc_ctl
  command to allow programmatic, command line and/or scripted
  optimization of wksp utilization.

- "query full" now can find all wksp partitions in use by the allocator,
  disambiguate large user wksp allocations from large superblock wksp
  allocations used to aggregate smaller user allocations and give
  complete statistics large user allocations.

- Slight implementation tweak and documentation update to cover optimally
  complex threading cases (e.g. malloc in one more producer threads and
  free in one more consumer threads).

- Other very minor cleanups

These all come at zero overhead (in space, time or concurrency) to the
existing fd_alloc.

util: remove redundant fd_tile.cxx

bazel: fix build for help compile data

config: load optional configs via EXTRAS var

config: add llvm-cov profile

Adds build profile for LLVM-based code coverage.

shmem: fix sign conversion bug

error: conversion to 'unsigned int' from 'int' may change the sign of the result [-Werror=sign-conversion]
  389 |   if( page_sz==FD_SHMEM_HUGE_PAGE_SZ     ) flags |= MAP_HUGETLB | MAP_HUGE_2MB;

config: source libbpf from pkg-config

config: find bash from PATH

nix-build does not support /bin/bash

nix: add default and shell profile

ci: basic make-based unit testing

- contrib/unit_tests.txt: Adds simple list of unit tests
  that can run without shared memory / allocations
- contrib: also build for linux_clang_x86_64
- contrib: run make-built tests via parallel

Note that the default GitHub CI runner does not have SHA-NI extensions
so test_bmtree{20,32}, test_poh, test_sha256 are omitted. To be fixed at
a later date.

ci: remove bazel_{build,test}

CI is now provided by our Nix/Make config.

treewide: remove Bazel support

ci: add make_coverage job

util: add fd_cstr_to_ip4_addr

git: add vim, vimdiff items to gitignore

Added wksp usage summaries and related tweaks

- By popular demand, added fd_wksp_usage API and "usage" command
  for getting summary usage reports programmatically and via command
  line.

- Tangentially related (because it could exploit the same tag set
  APIs added for usage), tweaked the fd_wksp_tag_free API to support
  freeing sets of tags at the same algo efficiency as a single tag.

- Tweaked test_wksp to allow unit tests to use an anonymous wksp
  to simplify CI integration and tweaked test_alloc unit test to match
  (which gives it some more flexibility to explore TLB and NUMA
  effects).

build, ci: add make run-unit-test

ci: update test workflow to use make rules

fix,cleanup: fix test workflow and remove dedup unit test

ci: update coverage to run tests from make

ci: remove fd_log_path in coverage

ci: attempt to fix CI

util: rm pcap unit test from runnable unit test target

build: remove more broken unit tests that dont work on azure

ci: fix workflow name

ci: rm log unit test

Update make_coverage.yml

config: enable compiler color output

Sets the "-fdiagnostics-color=always" flag to make compile errors easier
to read.

Revert "config: enable compiler color output"

This reverts commit 116a1f19ff799173600defe0caad8afeb58d2a22.